import { useEffect, useState } from "react";
import { ArrowUpRight, Check, ChevronRight, ExternalLink, Image as ImageIcon, Inbox, LayoutDashboard, LogOut, Palette, Save, Settings2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

const tabs = [
  { id: "overview", label: "Overview", icon: LayoutDashboard },
  { id: "brand", label: "Brand & contact", icon: Palette },
  { id: "collections", label: "Collections", icon: Sparkles },
  { id: "gallery", label: "Project gallery", icon: ImageIcon },
  { id: "enquiries", label: "Enquiries", icon: Inbox },
];
const fallback = { brandName: "Sri Venkateswara Granites", tagline: "Crafted by Nature. Perfected by Us.", heroEyebrow: "Premium natural stone · Since 1998", heroTitle: "Stone with a point of view.", heroCopy: "Architectural granite selected for bold residences, refined hospitality, and spaces made to last generations.", aboutTitle: "The quiet confidence of exceptional stone.", aboutCopy: "From our yard to your project, every slab is inspected for character, consistency, and cut.", phone: "+91 98765 43210", whatsapp: "+91 98765 43210", email: "Shrivatsan@icloud.com", address: "12 Stoneworks Estate, Hosur Road, Bengaluru, Karnataka 560068", hours: "Mon–Sat · 9:30 AM — 6:30 PM", heroImage: "/images/hero.jpg", aboutImage: "/images/waterfall.jpg", logoImage: "/images/logo.jpg" };

type TabId = typeof tabs[number]["id"];

export default function Admin() {
  const [activeTab, setActiveTab] = useState<TabId>("overview");
  const contentQuery = trpc.admin.content.useQuery();
  const collectionsQuery = trpc.admin.collections.useQuery();
  const galleryQuery = trpc.admin.gallery.useQuery();
  const enquiriesQuery = trpc.admin.enquiries.useQuery();
  const utils = trpc.useUtils();
  const [content, setContent] = useState<any>(fallback);
  const saveContent = trpc.admin.saveContent.useMutation({ onSuccess: () => { toast.success("Brand details saved"); utils.site.content.invalidate(); }, onError: (error) => toast.error(error.message) });
  const saveCollection = trpc.admin.saveCollection.useMutation({ onSuccess: () => { toast.success("Collection saved"); collectionsQuery.refetch(); }, onError: (error) => toast.error(error.message) });
  const saveGallery = trpc.admin.saveGallery.useMutation({ onSuccess: () => { toast.success("Gallery item saved"); galleryQuery.refetch(); }, onError: (error) => toast.error(error.message) });
  const updateEnquiry = trpc.admin.updateEnquiry.useMutation({ onSuccess: () => { toast.success("Enquiry status updated"); enquiriesQuery.refetch(); } });
  useEffect(() => { if (contentQuery.data) setContent(contentQuery.data); }, [contentQuery.data]);
  const collections = collectionsQuery.data ?? [];
  const gallery = galleryQuery.data ?? [];
  const enquiries = enquiriesQuery.data ?? [];
  const setField = (key: string, value: string) => setContent((current: any) => ({ ...current, [key]: value }));

  return <DashboardLayout><div className="admin-shell"><header className="admin-header"><div><div className="admin-eyebrow">Content studio · {content.brandName}</div><h1 className="admin-title">Make the stone speak.</h1><p className="admin-subtitle">Everything your public site says, in one considered place.</p></div><div className="flex items-center gap-3"><a href="/" target="_blank" rel="noreferrer" className="admin-outline"><ExternalLink className="h-3.5 w-3.5" /> View site</a><Button onClick={() => setActiveTab("brand")} className="admin-gold"><Settings2 className="h-3.5 w-3.5" /> Edit site</Button></div></header><div className="admin-tabs">{tabs.map((tab) => { const Icon = tab.icon; return <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`admin-tab ${activeTab === tab.id ? "admin-tab-active" : ""}`}><Icon className="h-4 w-4" />{tab.label}</button>; })}</div>

    {activeTab === "overview" && <Overview content={content} collections={collections} gallery={gallery} enquiries={enquiries} setActiveTab={setActiveTab} />}
    {activeTab === "brand" && <section className="admin-section"><SectionHeading eyebrow="Brand & contact" title="The details behind the presence." description="Update the voice, contact information, and photography used across the public website." /><div className="admin-form-grid"><Field label="Brand name" value={content.brandName} onChange={(value: string) => setField("brandName", value)} /><Field label="Tagline" value={content.tagline} onChange={(value: string) => setField("tagline", value)} /><Field label="Phone" value={content.phone} onChange={(value: string) => setField("phone", value)} /><Field label="WhatsApp" value={content.whatsapp} onChange={(value: string) => setField("whatsapp", value)} /><Field label="Email" value={content.email} onChange={(value: string) => setField("email", value)} /><Field label="Hours" value={content.hours} onChange={(value: string) => setField("hours", value)} /><Field label="Hero image URL" value={content.heroImage} onChange={(value: string) => setField("heroImage", value)} /><Field label="About image URL" value={content.aboutImage} onChange={(value: string) => setField("aboutImage", value)} /><Field label="Logo image URL" value={content.logoImage} onChange={(value: string) => setField("logoImage", value)} /><label className="admin-field full"><span>Address</span><Textarea value={content.address} onChange={(event) => setField("address", event.target.value)} /></label><label className="admin-field full"><span>Hero eyebrow</span><Input value={content.heroEyebrow} onChange={(event) => setField("heroEyebrow", event.target.value)} /></label><label className="admin-field full"><span>Hero title</span><Input value={content.heroTitle} onChange={(event) => setField("heroTitle", event.target.value)} /></label><label className="admin-field full"><span>Hero copy</span><Textarea value={content.heroCopy} onChange={(event) => setField("heroCopy", event.target.value)} /></label><label className="admin-field full"><span>About title</span><Input value={content.aboutTitle} onChange={(event) => setField("aboutTitle", event.target.value)} /></label><label className="admin-field full"><span>About copy</span><Textarea value={content.aboutCopy} onChange={(event) => setField("aboutCopy", event.target.value)} /></label></div><div className="mt-8 flex justify-end"><Button onClick={() => saveContent.mutate(content)} disabled={saveContent.isPending} className="admin-gold"><Save className="h-4 w-4" />{saveContent.isPending ? "Saving…" : "Save brand details"}</Button></div></section>}
    {activeTab === "collections" && <section className="admin-section"><SectionHeading eyebrow="Collections" title="Curate the material library." description="The first three featured stones lead the public collection view. Update names, descriptions, finishes, and image URLs here." /><div className="grid gap-5">{collections.map((item: any, index: number) => <EditableCard key={item.id} index={index} title={item.name} imageUrl={item.imageUrl} onSave={(data: any) => saveCollection.mutate({ id: item.id, data })} fields={[{ label: "Name", key: "name", value: item.name }, { label: "Category", key: "category", value: item.category }, { label: "Finish", key: "finish", value: item.finish }, { label: "Image URL", key: "imageUrl", value: item.imageUrl }, { label: "Description", key: "description", value: item.description, textarea: true }]} />)}</div></section>}
    {activeTab === "gallery" && <section className="admin-section"><SectionHeading eyebrow="Project gallery" title="Keep the proof of work fresh." description="Showcase finished spaces, locations, and the material stories behind them." /><div className="grid gap-5">{gallery.map((item: any, index: number) => <EditableCard key={item.id} index={index} title={item.title} imageUrl={item.imageUrl} onSave={(data: any) => saveGallery.mutate({ id: item.id, data })} fields={[{ label: "Title", key: "title", value: item.title }, { label: "Location", key: "location", value: item.location }, { label: "Year", key: "year", value: item.year }, { label: "Image URL", key: "imageUrl", value: item.imageUrl }, { label: "Sort order", key: "sortOrder", value: String(item.sortOrder) }]} />)}</div></section>}
    {activeTab === "enquiries" && <section className="admin-section"><SectionHeading eyebrow="Enquiries" title="Conversations worth following up." description="A simple working inbox for every new project request from the public site." /><div className="overflow-hidden rounded-3xl border border-black/10 bg-white">{enquiries.length ? enquiries.map((item: any) => <div key={item.id} className="enquiry-row"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><span className="font-medium text-ink">{item.name}</span><Badge className={item.status === "new" ? "status-new" : "status-progress"}>{item.status}</Badge></div><div className="mt-2 text-sm text-ink/55">{item.projectType} · {item.phone} · {item.email}</div><p className="mt-3 max-w-2xl text-sm leading-6 text-ink/70">{item.message}</p></div><select className="admin-select w-36" value={item.status} onChange={(event) => updateEnquiry.mutate({ id: item.id, status: event.target.value })}><option value="new">New</option><option value="in-progress">In progress</option><option value="closed">Closed</option></select></div>) : <div className="empty-state"><Inbox className="h-7 w-7 text-gold" /><div><div className="font-serif text-2xl text-ink">No enquiries yet.</div><p className="mt-1 text-sm text-ink/50">When a visitor reaches out, it will appear here.</p></div></div>}</div></section>}
  </div></DashboardLayout>;
}

function Overview({ content, collections, gallery, enquiries, setActiveTab }: any) { return <section className="admin-section"><div className="overview-hero"><div><div className="admin-eyebrow">Good morning, studio.</div><h2 className="font-serif text-5xl leading-none tracking-[-0.05em] text-ivory">The showroom is<br /><span className="text-gold">ready for its next story.</span></h2><p className="mt-5 max-w-lg text-sm leading-6 text-ivory/55">A quick pulse on the content that shapes Sri Venkateswara Granites online.</p></div><div className="overview-mark"><img src={content.logoImage} alt="" /><span>SV</span></div></div><div className="overview-grid"><Stat label="Active collections" value={collections.length} note="Material stories live" icon={Sparkles} /><Stat label="Project features" value={gallery.length} note="Spaces on display" icon={ImageIcon} /><Stat label="New enquiries" value={enquiries.filter((item: any) => item.status === "new").length} note="Ready for a reply" icon={Inbox} /></div><div className="quick-actions"><button onClick={() => setActiveTab("brand")}><Palette /><span><strong>Update brand details</strong><small>Voice, contact, imagery</small></span><ChevronRight /></button><button onClick={() => setActiveTab("collections")}><Sparkles /><span><strong>Refresh a collection</strong><small>Make the library current</small></span><ChevronRight /></button><button onClick={() => setActiveTab("enquiries")}><Inbox /><span><strong>Review enquiries</strong><small>Keep the conversation moving</small></span><ChevronRight /></button></div></section> }
function Stat({ label, value, note, icon: Icon }: any) { return <div className="stat-card"><Icon className="h-5 w-5 text-gold" /><div className="mt-7 font-serif text-5xl text-ink">{value}</div><div className="mt-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-ink/55">{label}</div><div className="mt-5 text-xs text-ink/40">{note}</div></div> }
function SectionHeading({ eyebrow, title, description }: any) { return <div className="mb-10 flex flex-col justify-between gap-5 border-b border-black/10 pb-8 sm:flex-row sm:items-end"><div><div className="admin-eyebrow text-ink/40">{eyebrow}</div><h2 className="mt-3 font-serif text-5xl leading-none tracking-[-0.05em] text-ink">{title}</h2></div><p className="max-w-sm text-sm leading-6 text-ink/50">{description}</p></div> }
function Field({ label, value, onChange }: any) { return <label className="admin-field"><span>{label}</span><Input value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></label> }
function EditableCard({ index, title, imageUrl, fields, onSave }: any) { const [values, setValues] = useState<any>(() => Object.fromEntries(fields.map((field: any) => [field.key, field.value]))); useEffect(() => setValues(Object.fromEntries(fields.map((field: any) => [field.key, field.value]))), [title]); return <div className="editable-card"><div className="editable-preview"><img src={values.imageUrl || imageUrl} alt="" /><div className="editable-number">0{index + 1}</div></div><div className="editable-fields"><div className="mb-5 flex items-center justify-between"><div><div className="admin-eyebrow text-ink/35">Material / entry {index + 1}</div><h3 className="mt-1 font-serif text-3xl text-ink">{values.name || values.title}</h3></div><Button onClick={() => onSave({ ...values, ...(values.sortOrder ? { sortOrder: Number(values.sortOrder) } : {}) })} className="admin-gold"><Check className="h-4 w-4" /> Save</Button></div><div className="grid gap-4 sm:grid-cols-2">{fields.map((field: any) => <label key={field.key} className={`admin-field ${field.textarea ? "full" : ""}`}><span>{field.label}</span>{field.textarea ? <Textarea value={values[field.key] ?? ""} onChange={(event) => setValues((current: any) => ({ ...current, [field.key]: event.target.value }))} /> : <Input value={values[field.key] ?? ""} onChange={(event) => setValues((current: any) => ({ ...current, [field.key]: event.target.value }))} />}</label>)}</div></div></div> }
