export const DEFAULT_CONTENT = {
  brandName: "Sri Venkateswara Granites",
  tagline: "Crafted by Nature. Perfected by Us.",
  heroEyebrow: "INDIAN GRANITE EXPORTER",
  heroTitle: "Sri Venkateswara Granites.",
  heroCopy: "Premium Indian granite products manufactured and prepared for international markets.",
  aboutTitle: "NATURE CREATES IT. WE PERFECT IT.",
  aboutCopy: "From raw granite selection to cutting, shaping, polishing, finishing and export packaging, every stage is handled with attention to detail.",
  phone: "9790613468",
  whatsapp: "9790613468",
  email: "sales.svgranites@gmail.com",
  address: "NO.951/3,Poovallikuppam Village Kadampathur Block, Post, Mappedu, Chennai, Tamil Nadu 602105",
  hours: "Mon–Sat · 9:30 AM — 6:30 PM",
  heroImage: "/images/hero-quarry.jpg",
  heroImage2: "/images/hero-quarry.jpg",
  aboutImage: "/images/craft-cutting.jpg",
  logoImage: "/images/logo.jpg",
  heroSubtext: "Premium Indian granite products manufactured and prepared for international markets.",
  facilityImage1: "/images/hero-quarry.jpg",
  facilityImage2: "/images/craft-cutting.jpg",
  facilityImage3: "/images/slabs-warehouse.jpg",
  facilityImage4: "/images/monument-headstone.jpg",
  facilityImage5: "/images/vases-collection.jpg",
  facilityTitle: "From Quarry to Container",
  facilityCopy: "A state-of-the-art facility with advanced machinery and a skilled team, ensuring precision at every stage.",
  bannerImage: "/images/monument-headstone.jpg",
  mapsUrl: "",
  googleSheetUrl: "",
  productsEyebrow: "OUR PRODUCTS",
  productsTitle: "Crafted for Lasting Impressions",
  productsCopy: "From monumental structures to elegant accessories, our granite products are designed to meet the highest standards of quality and durability.",
  collectionsEyebrow: "STONE COLLECTION",
  collectionsTitle: "Nature's Beauty. In Every Shade.",
  collectionsCopy: "Explore our premium range of granite stones, known for their unique patterns, colours and durability.",
  finishesEyebrow: "SURFACE FINISHINGS",
  finishesTitle: "The Art of Every Surface.",
  finishesCopy: "From mirror-polished luxury to rugged flamed textures — each finish transforms stone into a distinct architectural statement.",
  whyChooseEyebrow: "WHY SV GRANITES",
  whyChooseTitle: "The Right Partner for Your Stone Needs.",
  whyFeature1Title: "Direct Manufacturing",
  whyFeature1Desc: "Work directly with the source.",
  whyFeature2Title: "Consistent Quality",
  whyFeature2Desc: "Material and finish checked before dispatch.",
  whyFeature3Title: "Custom Production",
  whyFeature3Desc: "Tailored to your requirements.",
  whyFeature4Title: "Export Packaging",
  whyFeature4Desc: "Safe for international transport.",
  whyFeature5Title: "Responsive Communication",
  whyFeature5Desc: "Clear coordination from enquiry to shipment.",
  whyFeature6Title: "Long-Term Partnerships",
  whyFeature6Desc: "Built on trust and reliability.",
  globalReachEyebrow: "GLOBAL REACH",
  globalReachTitle: "FROM INDIA, MADE FOR THE WORLD.",
  globalReachCopy: "Manufactured in South India · Prepared for international buyers.",
  galleryEyebrow: "GALLERY",
  galleryTitle: "Stone in Every Frame.",
  enquiryTitle: "LOOKING FOR THE RIGHT STONE?",
  enquiryCopy: "Tell us what you're looking for. We'll help you find the right material, finish and specification.",
  bannerTitle: "STONE THAT LASTS. PARTNERSHIPS THAT GROW.",
  bannerSubtitle: "South India · India",
  metric1Val: "25+",
  metric1Label: "Years of Experience",
  metric2Val: "Export Ready",
  metric2Label: "International Packaging",
  metric3Val: "Quality Focused",
  metric3Label: "Every Order Inspected",
  metric4Val: "Direct Manufacturer",
  metric4Label: "From India",
  footerCopy: "All rights reserved.",
  whatsappTemplate: "Hello SV Granites, I visited your website and would like to enquire about your granite products and export pricing.",
  emailSubjectTemplate: "Enquiry regarding Granite Products & Supply - SV Granites",
  emailBodyTemplate: "Dear SV Granites Team,\n\nI visited your website and would like to enquire regarding your natural stone collection and pricing.\n\nProject details:\n\nThank you!",
};

export const DEFAULT_COLLECTIONS = [
  { name: "INDIAN BLACK GRANITE", category: "Signature Black", description: "Deep graphite · Mineral rhythm\nTimeless elegance", finish: "Leathered / Polished", imageUrl: "/images/indian-black.jpg", isFeatured: 1, sortOrder: 1, isVisible: 1 },
  { name: "ABSOLUTE BLACK GRANITE", category: "Architectural Slabs", description: "Deep black · Consistent texture\nHigh polish", finish: "Polished", imageUrl: "/images/absolute-black.jpg", isFeatured: 1, sortOrder: 2, isVisible: 1 },
  { name: "STEEL GREY GRANITE", category: "Cool Greys", description: "Layered grey · Sculptural presence\nPolished finish", finish: "Polished", imageUrl: "/images/steel-grey.jpg", isFeatured: 1, sortOrder: 3, isVisible: 1 },
  { name: "BLACK GALAXY GRANITE", category: "Sparkling Darks", description: "Sparkling darks · Radiant golden flecks\nHigh durability", finish: "Polished", imageUrl: "/images/black-galaxy.jpg", isFeatured: 1, sortOrder: 4, isVisible: 1 },
  { name: "TAN BROWN GRANITE", category: "Earthy Browns", description: "Warm brown · Distinctive pattern\nVersatile application", finish: "Versatile", imageUrl: "/images/tan-brown.jpg", isFeatured: 1, sortOrder: 5, isVisible: 1 },
];

export const DEFAULT_GALLERY = [
  { title: "", location: "", year: "", imageUrl: "/images/indian-black.jpg", sortOrder: 1, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/absolute-black.jpg", sortOrder: 2, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/steel-grey.jpg", sortOrder: 3, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/black-galaxy.jpg", sortOrder: 4, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/tan-brown.jpg", sortOrder: 5, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/slabs-warehouse.jpg", sortOrder: 6, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/monument-headstone.jpg", sortOrder: 7, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/vases-collection.jpg", sortOrder: 8, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/craft-cutting.jpg", sortOrder: 9, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/hero-quarry.jpg", sortOrder: 10, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/noir-vein.jpg", sortOrder: 11, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/waterfall.jpg", sortOrder: 12, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/feature-wall.jpg", sortOrder: 13, isVisible: 1 },
  { title: "", location: "", year: "", imageUrl: "/images/cloud-ledger.jpg", sortOrder: 14, isVisible: 1 },
];

export const DEFAULT_PRODUCTS = [
  { name: "GRANITE SLABS", description: "Premium granite surfaces selected for consistency, colour and finish.", imageUrl: "/images/slabs-warehouse.jpg", sortOrder: 1, isVisible: 1 },
  { name: "GRANITE MONUMENTS", description: "Precision-crafted memorial products designed for international markets.", imageUrl: "/images/monument-headstone.jpg", sortOrder: 2, isVisible: 1 },
  { name: "GRANITE VASES", description: "Elegant granite accessories crafted for memorial and landscaping applications.", imageUrl: "/images/vases-collection.jpg", sortOrder: 3, isVisible: 1 },
];

export const DEFAULT_FINISHES = [
  { name: "POLISHED FINISH", tagline: "High gloss mirror reflection", badge: "Classic Elegance", description: "Brings out the deepest color saturation, crystalline depth, and mineral contrast. Impervious and pristine.", imageUrl: "/images/absolute-black.jpg", sortOrder: 1, isVisible: 1 },
  { name: "HONED FINISH", tagline: "Smooth matte velvet surface", badge: "Architectural Satin", description: "Non-reflective satin touch with subtle diffusion. Ideal for contemporary interior walls, floors, and vanity counters.", imageUrl: "/images/noir-vein.jpg", sortOrder: 2, isVisible: 1 },
  { name: "FLAMED FINISH", tagline: "Thermal textured slip-resistance", badge: "Exterior Grade", description: "Exposed to intense high-temperature flame causing surface crystals to burst into a rough, non-slip textured face.", imageUrl: "/images/steel-grey.jpg", sortOrder: 3, isVisible: 1 },
  { name: "LEATHERED FINISH", tagline: "Tactile undulating leather feel", badge: "Warm Tactility", description: "Diamond-tipped brush texturing that retains natural grain contour while offering a warm, soft antique grip.", imageUrl: "/images/tan-brown.jpg", sortOrder: 4, isVisible: 1 },
  { name: "BUSH HAMMERED FINISH", tagline: "Uniformly pitted rustic texture", badge: "Heavy Duty", description: "Hydraulic impact chiseling produces an evenly pitted stone relief. Perfect for outdoor walkways, steps, and plazas.", imageUrl: "/images/cloud-ledger.jpg", sortOrder: 5, isVisible: 1 },
  { name: "WATERJET FINISH", tagline: "Micro-etched natural stone relief", badge: "Modern Textured", description: "High-pressure hydrodynamic washing that preserves the stone's genuine color tone while generating non-skid relief.", imageUrl: "/images/waterfall.jpg", sortOrder: 6, isVisible: 1 },
  { name: "CUT-TO-SIZE & EDGE PROFILING", tagline: "CNC bevel, bullnose & mitred joints", badge: "Custom Fabrication", description: "Custom precision fabrication according to international architectural blueprints, monument specs, and facade details.", imageUrl: "/images/feature-wall.jpg", sortOrder: 7, isVisible: 1 },
];

export const DEFAULT_SECTION_VISIBILITY: Array<{ sectionKey: string; isVisible: number }> = [
  { sectionKey: "hero", isVisible: 1 },
  { sectionKey: "about", isVisible: 1 },
  { sectionKey: "products", isVisible: 1 },
  { sectionKey: "collections", isVisible: 1 },
  { sectionKey: "finishes", isVisible: 1 },
  { sectionKey: "craft", isVisible: 1 },
  { sectionKey: "gallery", isVisible: 1 },
  { sectionKey: "facility", isVisible: 1 },
  { sectionKey: "contact", isVisible: 1 },
];
